version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "setup.py" }}
            - v1-dependencies-{{ .Branch }}
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install .
      - save_cache:
          paths:
            - ./vend
          key: v1-dependencies-{{ .Branch }}-{{ checksum "setup.py" }}
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest --junitxml=test-reposts/junit.xml
      - store_test_results:
          path: test-reports
